name: build and deploy webapp

env:
  ARTIFACT_NAME: csye6225-webapp-6.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

on:
  workflow_dispatch:
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package
      - name: Build Deployment Artifact
        run: |
          mkdir codedeploy_artifact
          zip -r ${{ env.ARTIFACT_NAME }} ./target/user-0.0.1-SNAPSHOT.jar codedeploy_scripts/*.sh appspec.yml cloudwatch-config.json
          pwd
          ls -al
          mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact
          ls -al
          pwd
          cd codedeploy_artifact
          pwd
          ls -al
          cd ..
          pwd
          ls -al
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws-access-key-id}}
          aws-secret-access-key: ${{ env.aws-secret-access-key}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy Artifact S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_CODE_DEPLOY_BUCKET }}
      - name: code Deployment Api call
        run: |
          aws deploy register-application-revision --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} --s3-location bucket=codedeploy.prod.suheel.me,bundleType=zip,key=csye6225-webapp-6.zip
          aws deploy create-deployment --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} --deployment-group-name ${{ env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME }} --s3-location bucket=codedeploy.prod.suheel.me,bundleType=zip,key=csye6225-webapp-6.zip --deployment-config-name CodeDeployDefault.AllAtOnce
